language: python
cache: 
  - pip
  - npm

python:
  - "3.6"

git:
    submodules: false

before_install:
    # - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

install:
    - pip install -r requirements.txt
    - pip install nose2 flake8 pylint codecov


before_script: # configure a headless display to test plot generation
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

script: make test

after_success:
    - codecov --token c0b8d51d-0f0e-4628-ab28-0d0607e3101a
    # - coveralls

branches:
  only:
  - master

notifications:
  email: false
